[NoDelete]
interface Globals {
	[Internal="hlForgeInitialize", Static]
	bool initialize(String name);
};

[Destruct=""]
interface Queue {
	[CObject, Internal="waitQueueIdle"] void waitIdle();

};

interface SwapChain {

};


[Destruct="destroyRenderer"]
interface Renderer {
	[Substitute="createRenderer"] void Renderer(String name);

	[CObject] Queue createQueue();

	[CObject] void removeQueue(Queue pGraphicsQueue);
};

[Internal="SDL_Window", NoDelete]
interface Window {
	[CObject] SwapChain createSwapChain(Renderer renderer, Queue queue, int width, int height, int count, bool hdr10);	
};
